### ISSUE TITLE
fix(bench): bench/issue61_prune_batch.py が PhotonInference(tokenizer=...) の API 変更に未追従

### ISSUE THREAD

**Issue by Kewton** [Kewton/photon-mlx#72]
## 現象

#58 で `PhotonInference.__init__(self, model, cfg, tokenizer)` と必須引数が増えたが、`bench/issue61_prune_batch.py:242` が古い API（`PhotonInference(model, cfg)`）のままで実行時に TypeError。

## 再現

\`\`\`
$ python bench/issue61_prune_batch.py --n-chunks 32 --max-len 256 --warmup 1 --measure 2
...
TypeError: PhotonInference.__init__() missing 1 required positional argument: 'tokenizer'
\`\`\`

## 対策

`bench/issue61_prune_batch.py:run_benchmark()` で `_TokenAdapter`（`photon_mlx/tests/conftest.py` と同等）を作成して PhotonInference に渡す。同様の問題が `bench/kv_cache_speedup.py` にもないか確認必要（KV cache benchmark は動作したため不要かも）。

## 優先度

低。pytest の単体テストで correctness は担保済み。

Related to #58, #61.

**Comment by Kewton** [comment]
Fixed in PR #76 (Issue #63). Verified:

```
python bench/issue61_prune_batch.py --n-chunks 8 --max-len 128 --warmup 1 --measure 2
```

Output: `speedup: p50=1.264x ... selection_match=True` — bench runs to completion, no more `PhotonInference.__init__() missing 1 required positional argument: 'tokenizer'` error.

The fix added a `_StubTokenizer` helper at bench/issue61_prune_batch.py:52 that mirrors the baseline stub tokenizer contract and is now passed as the third argument to `PhotonInference(model, cfg, tokenizer)` (the API change introduced by #58).
